# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SensorService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SensorService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\x12\x06sensor\"\x07\n\x05\x45mpty\"3\n\x0fReadingResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"<\n\x0fHistoryResponse\x12)\n\x08readings\x18\x01 \x03(\x0b\x32\x17.sensor.ReadingResponse2\x81\x01\n\rSensorService\x12:\n\x10GetLatestReading\x12\r.sensor.Empty\x1a\x17.sensor.ReadingResponse\x12\x34\n\nGetHistory\x12\r.sensor.Empty\x1a\x17.sensor.HistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_READINGRESPONSE']._serialized_start=40
  _globals['_READINGRESPONSE']._serialized_end=91
  _globals['_HISTORYRESPONSE']._serialized_start=93
  _globals['_HISTORYRESPONSE']._serialized_end=153
  _globals['_SENSORSERVICE']._serialized_start=156
  _globals['_SENSORSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
